trigger:
 - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    
    steps:      
    - task: GitVersion@5
      inputs:
        versionSpec: '5.x'

    - task: UseDotNet@2
      displayName: 'use .net core sdk'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        includePreviewVersions: true
        
    - task: DotNetCoreCLI@2
      displayName: Build with dotnet
      inputs:
        command: 'build'

    - task: DotNetCoreCLI@2
      displayName: Test with dotnet
      inputs:
        command: 'test'
    
    - task: PowerShell@2
      name: AssignVersion
      inputs:
        targetType: 'inline'
        script: | 
          Write-Host "##vso[task.setvariable variable=version;isOutput=true]$(GitVersion.SemVer)"
          echo $(GitVersion.SemVer)

  - job: BuildAndPush
    displayName: BuildAndPush
    dependsOn: [Build]
    pool:
      vmImage: ubuntu-latest
    variables:
        dockerGitVersion: $[ dependencies.Build.outputs['AssignVersion.version'] ]

    steps:
    - task: Docker@2
      displayName: BuildAndPush
      inputs:
        command: buildAndPush
        repository: 'blazor-conf-2022-devops'
        containerRegistry: 'blazorconfregistry'
        tags: |
          $(dockerGitVersion)
          latest

- stage: DeployStage
  displayName: Deploy Stage
  dependsOn: [Build]
  variables: 
    dockerGitVersion: $[ stageDependencies.Build.Build.outputs['AssignVersion.version'] ]
  pool:
    vmImage: ubuntu-latest
  
  jobs:
  - deployment: DeployStage
    environment: 'Stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(659021ae-a62f-4259-adb4-5a094b114490)'
              appName: 'blazorconf2022-ci-cd-container2'
              deployToSlotOrASE: true
              resourceGroupName: 'BlazorConf2022'
              slotName: 'Stage'
              containers: 'blazorconf2022.azurecr.io/blazor-conf-2022-devops:$(dockerGitVersion)'

- stage: DeployProd
  displayName: Deploy Production
  dependsOn: [Build, DeployStage]
  variables: 
    dockerGitVersion: $[ stageDependencies.Build.Build.outputs['AssignVersion.version'] ]
  pool:
    vmImage: ubuntu-latest
  
  jobs:
  - deployment: DeployStage
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(659021ae-a62f-4259-adb4-5a094b114490)'
              appName: 'blazorconf2022-ci-cd-container2'
              containers: 'blazorconf2022.azurecr.io/blazor-conf-2022-devops:$(dockerGitVersion)'


