name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with dotnet
        run: dotnet test

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-stage:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Stage'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App dev
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blazorconf2022-ci-cd-code'
          slot-name: 'Stage'
          publish-profile: ${{ secrets.PUBLISHPROFILE  }}
          package: .
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build,deploy-stage]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App dev
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blazorconf2022-ci-cd-code'
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISHPROFILE  }}
          package: .
