name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
        
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: test with dotnet
        run: dotnet test
        
      - name: Create tag repository
        run: |
          git tag "${{ steps.gitversion.outputs.SemVer }}"
          git push origin "${{ steps.gitversion.outputs.SemVer }}"
          
    outputs:
      version: ${{ steps.gitversion.outputs.SemVer}}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: blazorconf2022.azurecr.io
        username: ${{ secrets.container_registry_username }}
        password: ${{ secrets.container_registry_password }}

    - name: Build and push core image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          blazorconf2022.azurecr.io/blazor-conf-2022:${{ needs.build.outputs.version }}
          blazorconf2022.azurecr.io/blazor-conf-2022:latest
        push: true
