name: Trigger auto deployment for containerapp container-app-blazor-conf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-blazor-conf-AutoDeployTrigger-23c9892e-1f2b-4d9a-bd33-df17734b195a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: blazorconf2022.azurecr.io
          username: ${{ secrets.CONTAINERAPPBLAZORCONF_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPBLAZORCONF_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: blazorconf2022.azurecr.io/container-app-blazor-conf:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPBLAZORCONF_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n container-app-blazor-conf -g BlazorConf2022 --server blazorconf2022.azurecr.io --username  ${{ secrets.CONTAINERAPPBLAZORCONF_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPBLAZORCONF_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-blazor-conf -g BlazorConf2022 --image blazorconf2022.azurecr.io/container-app-blazor-conf:${{ github.sha }}
