name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - uses: actions/checkout@v2
      name: Check out code
    
    - uses: actions/setup-gitversion@v1.0.0
      id: gitversion
      with:
        gitversion-version: 5.1.1
    - run: GitVersion

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: blazor-conf-2022
        tags: ${{ steps.gitversion.outputs.SemVer }}, latest
        registry: blazorconf2022.azurecr.io
        username: ${{ secrets.container_registry_username }}
        password: ${{ secrets.container_registry_password }}
