name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.container_registry_username }} 
        # Container registry password
        password: ${{ secrets.container_registry_password }}
        # Container registry server url
        login-server: 'blazorconf2022.azurecr.io'
        
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        repository: 'blazor-conf-2022'
        # Github access token for private repositories
        git_access_token: ${{ secrets.GITHUB_TOKEN }}
        # Docker image tag, default to the commit SHA
        tag: 'latest'
